instaclone/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("post.urls", namespace="post")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)  #for image show

post/urls.py
from django.urls import path 
from post.views import home_feed, add_post, edit_post

app_name = "post"
urlpatterns = [
    path("feed/", home_feed, name="home"),
    path("create-post/", add_post, name="add_post"),
    path("change-post/<int:post_id>/", edit_post, name="edit_post"),
]

chat/models.py
from django.db import models

# Create your models here.

post/models.py
from django.db import models
from django.conf import settings
# Create your models here.
class PostStatus(models.TextChoices):
    PUBLIC = ("public", "Public")
    PRIVATE = ("private", "Private")

class Post(models.Model):
    picture = models.ImageField(upload_to="posts/")
    caption = models.CharField(max_length=100, blank=True, null=True)
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, blank=True, null=True
    )
    status = models.CharField(
        max_length=100,
        choices=PostStatus.choices,
        default=PostStatus.PRIVATE
    )

    
    class Meta:
        verbose_name = "Post"
        verbose_name_plural = "Posts"

    def __str__(self):
        return str(self.id)
    
class Like(models.Model):
    is_likes = models.BooleanField(default=False)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)

    def __str__(self):
        return str(self.id)

    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, blank=True, null=True
    )

    
class Comment(models.Model):
    text = models.CharField(max_length=150)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)

    def __str__(self):
        return self.text
    
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, blank=True, null=True
    )

useraccount/models.py
from django.db import models

# Create your models here.
from django.contrib.auth.models import AbstractUser

class User(AbstractUser):
    contact = models.CharField(max_length=255, blank=True, default="")
    address = models.CharField(max_length=255, blank=True, default="")
    profile_picture = models.ImageField(
        upload_to="profile_pictures/",
        blank=True,
        null=True,
    )

post/forms.py
from django import forms
from post.models import Post
# class TestForm(forms.Form):
#     first_name = forms.CharField(max_length=100)
#     last_name = forms.CharField(max_length=100)

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ["picture", "caption",]
        #exclude = ["user",]

chat/views.py
from django.shortcuts import render

# Create your views here.

post/views.py
from django.shortcuts import render, reverse, get_object_or_404
from post.models import Post
# from post.forms import TestForm
from post.forms import PostForm
from django.http import HttpResponseRedirect, HttpResponse, Http404
# Create your views here.
def home_feed(request):
    posts = Post.objects.all().order_by("-id")
    context = {"posts": posts }
    return render(request, "home_feed.html", context)
def add_post(request):
    # form = TestForm(request.POST or None)
    # if form.is_valid():  #for check validation
    #     print(form.cleaned_data)
    # context = {"form":form}
    form = PostForm(request.POST or None, request.FILES or None)
    if form.is_valid():
        # print(form.cleaned_data)
        form.save()
        return HttpResponseRedirect(reverse("post:home"))
    context = {"form":form}
    return render(request, "add_post.html", context)

def edit_post(request, post_id):
    # try:
    #     post = Post.objects.get(id=post_id)
    # except Post.DoesNotExist:
    #     raise Http404("such a page does not exist")
    post= get_object_or_404(Post, id=post_id)
    form = PostForm(request.POST or None, request.FILES or None, instance=post)
    if form.is_valid():
        form.save()
        return HttpResponseRedirect(reverse("post:home"))
    context = {"form": form }
    return render(request, "edit_post.html", context)

useraccount/views.py
from django.shortcuts import render

# Create your views here.

post/templates/add_post.html
{% extends 'base_site.html' %}
{% block content %}
<div class="row ">
    <div class="col-sm-12 col-md-2 col-lg-2"></div>
    <div class="col-sm-12 col-md-8 col-lg-8">
        <form method="post" enctype="multipart/form-data">
          {% csrf_token %}
         {{form}}
        <button type="submit" name="submit" value="submit">Submit</button>
        </form>
    </div>
    <div class="col-sm-12 col-md-2 col-lg-2"></div>

</div>

{% endblock content %}

post/templates/edit_post.html
{% extends 'base_site.html' %}
{% block content %}
<div class="row ">
    <div class="col-sm-12 col-md-2 col-lg-2"></div>
    <div class="col-sm-12 col-md-8 col-lg-8">
        <h4>Edit Post</h4>
        <form method="post" enctype="multipart/form-data">
          {% csrf_token %}
         {{form}}
        <button type="submit" name="submit" value="submit">Submit</button>
        </form>
    </div>
    <div class="col-sm-12 col-md-2 col-lg-2"></div>

</div>

{% endblock content %}

post/templates/home_feed.html
{% extends 'base_site.html' %}
{% block content %}
<div class="row mt-2">
    <div class="col-sm-12 col-md-4 col-lg-4"></div>
    <div class="col-sm-12 col-md-4 col-lg-4">
        
            {% for post in posts %}
            
            <div  class="card mt-5 shadow">
                <div class="card-body">
        
                  <img class="w-100 img-responsive" src="{{ post.picture.url }}" alt="{{ post.caption}}">
                  <p>{{ post.caption }}</p>
                </div>
                <div class="card-footer">
                    <span>Like:1</span>
                    <span>Comment:2</span>
                    <div class="float-end">
                        <a class="btn btn-info btn-xs" href="{% url 'post:edit_post' post.id %}">Edit</a>
                    </div>
                </div>
            </div>
            {% endfor %}
        
        
    </div>
    <div class="col-sm-12 col-md-4 col-lg-4"></div>

</div>

{% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% if title %}
            {{title}}
        {% else %}
            Instagram Clone
        {% endif %}
    </title>
    {% block stylesheet %}
        <link rel="stylesheet" href="{% static 'css/style.css' %}">
    {% endblock stylesheet %}
</head>
<body>
    <div class="container-fluid">
        {% block main %}

        {% endblock main %}

    </div>
    {% block script %}
        <script type="text/javascript" src="{% static 'js/script.js' %}"></script>
    {% endblock script %}
</body>
</html>

templates/base_site.html
{% extends 'base.html' %}
{% block main %}
    {% include 'navbar.html' %}
    {% block content %}
    
    {% endblock content %}
{% endblock main%}

templates/navbar.html
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
      <a class="navbar-brand" href="{% url 'post:home' %}">Instaclone</a>
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'post:home' %}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Sign Up</a>
        </li>
        <li class="nav-item">
          <a class="nav-link " aria-disabled="true">Login</a>
        </li>
      </ul>
      <div class="d-flex">
        
        <a class="btn btn-outline-success btn-sm" href="{% url 'post:add_post' %}">Create</a>
      </div>
    </div>
  </div>
</nav>